Oksana
neatowebsolutions/artistdirectory pull request #14
Opened 2022-10-03 16:04 UTC by OxiBo

update a new artist whose profile was initially rejected

2022-10-04 17:42 UTC, chaddjohnson requested changes

2022-10-04 17:42 UTC, chaddjohnson commented on applications/directory/src/components/CreateProfileForm.js
> +                  console.log(reason);
Please remove `console.log()` call.

2022-10-04 17:42 UTC, chaddjohnson commented on services/directory-api/src/routes/updateNewArtist.js
> +      `/artists/edit/edit-profile-token/${editProfileToken}`,
This path should be `/artists/edit-profile-token/${editProfileToken}` (no `/edit`).

2022-10-04 17:42 UTC, chaddjohnson commented on services/artists-api/serverless.yml
> +          path: /artists/edit/edit-profile-token/{editProfileToken}
This path should be `/artists/edit-profile-token/${editProfileToken}` (not `/edit`).

2022-10-04 17:42 UTC, chaddjohnson commented on applications/directory/src/components/CreateProfileForm.js
> +          console.log(art);
Need to remove `console.log()`.

2022-10-04 17:42 UTC, chaddjohnson commented on applications/directory/src/components/CreateProfileForm.js
> +          const art = await updateNewArtist(data, artist.editProfileToken);
Once `console.log()` is removed, no need for `const art` here.

2022-10-04 17:42 UTC, chaddjohnson commented on applications/directory/src/components/CreateProfileForm.js
>            console.log(data);
Also let's remove this `console.log()`.

2022-10-04 17:43 UTC, chaddjohnson commented
@OxiBo Please see refactored changes here: https://github.com/neatowebsolutions/artistdirectory/commit/3176fd3a1742106357653ab5a8b1a515851e0af6

2022-10-05 14:02 UTC, OxiBo commented on services/artists-api/serverless.yml
> +          path: /artists/edit/edit-profile-token/{editProfileToken}
that is correct. Forgot to change it. It was part of debugging process

2022-10-05 14:03 UTC, OxiBo commented on services/directory-api/src/routes/updateNewArtist.js
> +      `/artists/edit/edit-profile-token/${editProfileToken}`,
that is correct. Forgot to change it. It was part of debugging process

2022-10-05 14:04 UTC, OxiBo commented on applications/directory/src/components/CreateProfileForm.js
> +          const art = await updateNewArtist(data, artist.editProfileToken);
Also was part of debugging. Will be deleted

2022-10-05 14:04 UTC, OxiBo commented on applications/directory/src/components/CreateProfileForm.js
>            console.log(data);
ok

2022-10-05 14:46 UTC, OxiBo commented on applications/directory/src/components/CreateProfileForm.js
> +                  console.log(reason);
done

2022-10-06 01:40 UTC, merged